### PR TITLE
java_swing_awt_example

### PR DESCRIPTION
**Pull request by neha-lisa**
An Example of the awt swing for a hello world program

### CODE REVIEW

**Comment by thomasrockhu** [comment]
@neha-lisa, closing as I'm not sure this is relevant

**Comment by neha-lisa** [comment]
I legit made a mistake while adding the file.

**Comment by thomasrockhu** [comment]
@neha-lisa no worries, feel free to reopen!

**Comment by neha-lisa** [comment]
Thanks for understanding sir.

**Pull request closed without merging**
