### PR TITLE
Upgrade jacoco version

### PR DESCRIPTION
**Pull request by konohiroaki**
Updating a jacoco plugin version

### CODE REVIEW

**Comment by konohiroaki** [comment]
I first created this for issue 6 but I was misunderstanding the problem. I tried with newer jacoco version and it worked but actually with older jacoco version it also worked. I changed the purpose of this PR for just upgrading the version (or should I close to avoid upgrading for no reason?)

**Comment by stevepeak** [comment]
We do like keeping the version up-to-date 👍 Thanks for pointing this out. You are welcome to re-open.

**Comment by konohiroaki** [comment]
Thank you. But sorry I mistakenly deleted the fork once thus this PR lost the link and cannot reopen. May I create another PR with same fix?

**Comment by stevepeak** [comment]
Certainly 👍 Thank you

**Pull request closed without merging**
